### ISSUE TITLE
import { adal } from 'adal-angular';  - doesn't work in other project

### ISSUE THREAD

**Issue by pvsherman** [jcmontx/angular5-adal-example#2]
Your project runs fine OTB. Thank you.

But when I try to move code into my project I run into issue where import:
**import { adal } from 'adal-angular';** gives me an error:
_Could not find a declaration file for module 'adal-angular'. '..../node_modules/adal-angular/lib/adal.js' implicitly has 'any' type. Try '**npm install `@types/adal-angular`**' if it exists or add a  new declaration (.d.ts) file containing  declare module 'adal-angular'_

**Update:**
I didn't figure out why the error above happened but I just replaced your code:
```
const config: adal.Config = {                           
  tenant: 'XXXXXX.onmicrosoft.com',                      
  clientId: 'XXXXXX-XXXXXXXX-XXXXXXXXX'    
}
```
 with this:
```
_const config = {
    tenant: 'xxxxx.onmicrosoft.com',
    clientId: '9bc158ed-13d5-aedb-ba00-4c9a1d6d8384',
    postLogoutRedirectUri: 'http://localhost:62001/'
}_
```
It doesn't need reference to adal-angular.

**Comment by kaburkett** [comment]
If I install the types as recommended, line 4 has to be modified to:

    import * as adal from 'adal-angular';

Then I can actually get the types by making config a type of adal.Options:

    const config: adal.Options = {                           
      tenant: 'wwwoodproducts.onmicrosoft.com',                      
      clientId: '9c906be6-7efc-40a7-a6a9-0801d3700801'    
    }  

The only problem is, when the types are installed it also breaks the adal5.service 

    ERROR in node_modules/adal-angular5/adal5.service.d.ts(1,10): error TS2305: Module '"C:/angular5-adal-example/node_modules/@types/adal-angular/index"' has no exported member 'adal'.

Because in the adal5 service on line 1:

    import { adal } from 'adal-angular';

Looks like unless we wanna fight an uphill battle just to maintain a type on this object, better to just implement it like you suggest? Might do a pull request with the adal import removed.
